---
- name: Run Slackin
  hosts: osas
  tasks:
    - name: useradd slackin
      user:
        name: slackin

    - name: Install Gulp (from NPM)
      shell: "npm install -g gulp"

    - name: Install now (from NPM)
      shell: "npm install -g slackin"

    - name: Run Slackin
      shell: 'slackin "performancecopilot" {{ hostvars[groups["osas"][0]]["slackin"] }}'
      args:
        chdir: /home/slackin/
